// `.env.ts` is generated by the `npm run env` command
import env from './.env';

export const environment = {
  production: true,
  version: env.npm_package_version,
  serverUrl: '/api',
  fakeServerUrl: 'http://127.0.0.1:3000/fakeapi',
  defaultLanguage: 'en-US',
  supportedLanguages: [
    'en-US',
    'en-Test'
  ]
};
